BikeShopWeb/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeShopWeb.Models;
using PagedList;

namespace BikeShopWeb.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProductCategories
        public ActionResult Index()
        {
            return View(db.ProductCategories.ToList());
        }

        public ActionResult getCategories()
        {
            return PartialView(db.ProductCategories.ToList());

        }


        // Find product by Category
        public ActionResult FindProduct(int? id, string sortBikes, string currentFilter, int? page, string searchString)
        {

            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortBikes) ? "Price_desc" : "";
            ViewBag.DateSortParam = sortBikes == "Date" ? "date_desc" : "Date";
            ViewBag.CurrentSort = sortBikes;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.currentFilter = searchString;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            ProductCategory productCategory = db.ProductCategories.Find(id);

            if (productCategory == null)
            {
                return HttpNotFound();
            }
            //var products = from p in db.Products
            //               select p;

            

            int pageSize = 9;
            int pageNumber = (page ?? 1);

            var Allproducts = from pc in productCategory.Product.ToPagedList(pageNumber, pageSize)
                              select pc;
            if (!String.IsNullOrEmpty(searchString))
            {
                Allproducts = Allproducts.Where(pc => pc.productName.Contains(searchString)
                                       || pc.productDescription.Contains(searchString));
            }

            switch (sortBikes)
            {
                case "Price_desc":
                    Allproducts = Allproducts.OrderByDescending(pc => pc.price);
                    break;
                case "date_desc":
                    Allproducts = Allproducts.OrderByDescending(pc => pc.ProductAdded);
                    break;
                case "Date":
                    Allproducts = Allproducts.OrderBy(pc => pc.ProductAdded);
                    break;
                default:
                    Allproducts = Allproducts.OrderBy(pc => pc.price);
                    break;
            }

            return View(Allproducts.ToPagedList(pageNumber, pageSize));

        }

        // GET: ProductCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // GET: ProductCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductCategoryID,categoryName,categoryNotes")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productCategory);
        }

        // GET: ProductCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductCategoryID,categoryName,categoryNotes")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        // GET: ProductCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BikeShopWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeShopWeb.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using PagedList;

namespace BikeShopWeb.Controllers
{
    //[Authorize]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //[AllowAnonymous]
        // GET: Products
        public ActionResult Index(string sortBikes, string currentFilter, int? page, string searchString)
        {
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortBikes) ? "Price_desc" : "";
            ViewBag.DateSortParam = sortBikes == "Date" ? "date_desc" : "Date";
            //ViewBag.KeyWordParam = string.IsNullOrEmpty
            ViewBag.CurrentSort = sortBikes;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.currentFilter = searchString;
            // string isloggedin = User.Identity.GetUserId();
           var products = from p in db.Products.Include(p => p.ApplicationUsers).Include(p => p.ProductCategory)
            select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.productName.Contains(searchString)
                                       || p.productDescription.Contains(searchString));
            }

            switch (sortBikes)
            {
                case "Price_desc":
                    products = products.OrderByDescending(p => p.price);
                    break;
                case "date_desc":
                    products = products.OrderByDescending(p => p.ProductAdded);
                    break;
                case "Date":
                    products = products.OrderBy(p => p.ProductAdded);
                    break;
                default:
                    products = products.OrderBy(p => p.price);
                    break;
            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult getCategories()
        {
            return PartialView(db.ProductCategories.ToList());

        }

        
        public ActionResult getProductsOfUser(int? id)
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUsersID = new SelectList(db.Users, "Id", "Email");
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "categoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,productName,productDescription,price,ProductCategoryID,ApplicationUsersID,ProductAdded, UploadedFile")] Product product, HttpPostedFileBase UploadedFile)
        {
            if(UploadedFile == null)
            {
                product.ImageUrl = "/NoImage/rsz_default.png";
                product.ProductAdded = DateTime.Now;
                product.ApplicationUsersID = User.Identity.GetUserId();
                db.Products.Add(product);
                db.SaveChanges();
                ViewBag.SuccessMsg = "Your bike has been successfully added";
                return RedirectToAction("Index");
            }
            else
            {
                var ext = Path.GetExtension(UploadedFile.FileName);
                string path = Server.MapPath("~/UploadedImages/");
                string name = Guid.NewGuid().ToString() + ext;
                UploadedFile.SaveAs(path + name);
                if (ModelState.IsValid)
                {
                    product.ImageUrl = "/UploadedImages/" + name;
                    product.ProductAdded = DateTime.Today;
                    product.ApplicationUsersID = User.Identity.GetUserId();
                    db.Products.Add(product);
                    db.SaveChanges();
                    ViewBag.SuccessMsg = "Your bike has been successfully added";
                    return RedirectToAction("Index");
                }
            }
            
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "categoryName", product.ProductCategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUsersID = new SelectList(db.Users, "Id", "Email", product.ApplicationUsersID);
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "categoryName", product.ProductCategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,productName,productDescription,price,ProductCategoryID,ApplicationUsersID")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUsersID = new SelectList(db.Users, "Id", "Email", product.ApplicationUsersID);
            ViewBag.ProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "categoryName", product.ProductCategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult UserProducts()
        {
            //id = User.Identity.GetUserId();


               
            return PartialView(db.Products.ToList());

        }
    }
}

BikeShopWeb/Views/Shared/FindProduct.cshtml
@model PagedList.IPagedList<BikeShopWeb.Models.Product>
@using PagedList.Mvc;

<head>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet">
    <!-- Paged List CSS-->
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <!-- Custom CSS -->
    <link href="~/Content/custom.css" rel="stylesheet">

</head>
<body>
    <h2>Find your new bike</h2>

    <div class="container">
        <!-- Searching panel/categories -->
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Categories</p>
                <div class="list-group">

                    @Html.Action("getCategories")

                </div>
            </div>
            <div class="col-md-9">
                <div class="Searching">

                    @using (Html.BeginForm("Index", "Products", FormMethod.Get))
                    {
                        <div class="form-inline">
                            <div class="form-group">
                                <label>Find by Key Word:</label>
                                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                                <button type="submit" class="btn btn-default">Search</button>
                            </div>

                        </div>
                    }
                    <div class="Sorting">
                        <label>Sort By:</label>
                        @Html.ActionLink("Newest", "FindProduct", new { SortBikes = ViewBag.DateSortParam, currenFilter = ViewBag.CurrentFilter }) <label> | </label>
                        @Html.ActionLink("Price", "FindProduct", new { SortBikes = ViewBag.PriceSortParam, currenFilter = ViewBag.CurrentFilter })
                    </div>
                </div>
                <!-- Fetching shop with items -->
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-sm-4 col-lg-4 col-md-4" id="product">
                            <div class="thumbnail">
                                <img src="@item.ImageUrl" alt="">
                                <h4><span class="label label-success pull-right">DKK @Html.DisplayFor(modelItem => item.price)</span></h4>

                                <div class="caption">
                                    <h4>
                                        <a>@Html.ActionLink(item.productName, "Details", "Products", new { id = item.ProductID }, null)</a>
                                    </h4>
                                    <p>@Html.DisplayFor(modelItem => item.productDescription)</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <br />
                <div class="Pages">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("Index",
                             new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                </div>
            </div>
        </div>
    </div>



    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>

BikeShopWeb/Views/Shared/UserProducts.cshtml
@model IEnumerable<BikeShopWeb.Models.Product>
<head>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet">

</head>
<body>
    @foreach (var item in Model)
    {
            <!-- List of Categories -->
        <div class="list-group-item">
            @Html.ActionLink(item.productName, "Edit", "Products", new { id = item.ProductID }, null) ||
            <label>
                @Html.ActionLink("Delete","Delete", "Products", new { id = item.ProductID }, null)
            </label>
        </div>

    }

</body>

BikeShopWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/custom.css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GET YOUR BIKE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("BUY A BIKE","Product","Home")</li>
                    <li>@Html.ActionLink("SELL A BIKE","SellBike","Home")</li>
                    <li>@Html.ActionLink("ABOUT US", "About", "Home")</li>
                    <li>@Html.ActionLink("CONTACT US", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>copyright &copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("mySection", required: false)
</body>
</html>

BikeShopWeb/Views/Shared/getCategories.cshtml
@model IEnumerable<BikeShopWeb.Models.ProductCategory>


<head>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet">

</head>
<body>
    @foreach (var item in Model)
    {
            <!-- List of Categories -->
            <div class="list-group-item">
            @Html.ActionLink(item.categoryName, "FindProduct", "ProductCategories", new { id = item.ProductCategoryID }, null)
            </div>
 
    }

</body>
